language: node_js
before_script: bower install ace-builds#master
script:
- docpad generate --env static
before_deploy: cd out
deploy:
  provider: cloudfiles
  username: devopsy
  api_key:
    secure: jC8iykmTJu3w1amcVaR5IZ8kjagNKCxkTD2LnLhxwboEnHkE6iTIuJFCmEDOQCwaKepc4dhAknLiD6lveXABP1DfY6ncnhaLJN7TAXQKEMsb5fQvfzSBUgMObPffdyvcZGDArBaGfLhFGIOv8LAtkRXwe67Cb+4kgEot8ExyJYg=
  region: ord
  container: pacto
  skip_cleanup: true
  on:
    repo: maxlinc/pacto-site
    branch: master

